# Generated by Django 3.2.5 on 2021-07-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=255)),
                ("tweet_url", models.URLField(max_length=255)),
                ("is_seguridad", models.BooleanField(null=True)),
                ("account", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
