# Generated by Django 3.2.5 on 2021-07-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
