# Generated by Django 3.2.6 on 2021-08-21 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_auto_20210815_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classification",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
