# Generated by Django 3.2.6 on 2021-09-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20210821_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hide_tweet',
            field=models.BooleanField(default=False),
        ),
    ]
