# Generated by Django 3.2.6 on 2021-09-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_hide_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='hide_tweet',
            field=models.BooleanField(default=False, help_text='Dejar de mostrar el tweet'),
        ),
    ]
